version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: db_container
    ports:
      - "3333:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}


  app:
    build:
      context: .
    container_name: fastapi_service
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  pg_data:
